# Copyright IBM Corp. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#

OrdererOrgs:
  - Name: Orderer2
    Domain: example.com
    EnableNodeOUs: true
    Specs:
      - Hostname: orderer2
        SANS:
          - localhost
