# Copyright IBM Corp. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#

OrdererOrgs:
  - Name: Orderer3
    Domain: example.com
    EnableNodeOUs: true
    Specs:
      - Hostname: orderer3
        SANS:
          - localhost
